### ISSUE TITLE
Problems assigning parties to projects (apparently timezone related)

### ISSUE THREAD

**Issue by jenshp** [moqui/HiveMind#12]
I am finding 2 problems when creating / updating project-party relations in /apps/hmadmin/User/EditProjects. Both seem to be related to timezone. Not sure whether this is a HiveMind, Mantle or Moqui issue but as it comes up in HiveMind I have added this issue here.

1. When creating a new association of a party to a project, the from_date is in the future, so the project does not appear in the users' project list.
2. When trying to modify an existing association of a party to a project, e.g. modifying the status, the entity-auto update service does not find the value. I assume this is due to a mismatch in the from_date field of the PK.

In the first case, I am not sure whether it could be a configuration issue because of a timezone mismatch between the users and the server's. But in the second case, regardless of the configured timezones, if I do not change the from_date (which I also cannot, because it is a PK of the table), I should be able to modify the values.

**Comment by jonesde** [comment]
Which versions of Moqui, Mantle, and HiveMind are you using?

**Comment by jenshp** [comment]
I am using the GIT versions, updated today:
* moqui c28f68663c0230c6e5bc9892af95cffa27087c3b
* mantle 73284b766c786b526b01509f9fa623b011106888
* HiveMind 093813dd086137fb7559a3e2697cae84fbab4e5c

Machine time zone: Chile/Continental (CLT): UTC-03
The users for which I have tested is john.doe (the test user created by default, with no changes) and a new user created through the web interface using TZ Chile/Continental. The user which logs in to make these changes is john.doe.
No config changes or anything.

I just made a fresh cleanAll, build, load, run. I am having difficulties reproducing the first part reported, but even logging in as john.doe, I cannot change the status of a project to party association.

To reproduce, I am using a clean DB with the standard test data and following steps:
1. log in as john.doe
2. select HiveMind Admin to get to the dashboard
3. select "Users"
4. select user "john.doe"
5. select "Projects" tab
6. try to change the single project role to status "Unassign"
Error is:

In entity-auto update service for entity [mantle.work.effort.WorkEffortParty] value not found, cannot update; using parameters [[html_scripts:[/assets/lib/jquery/jquery.min.js, /assets/lib/jquery/jquery-migrate-1.2.1.min.js, /assets/lib/jquery-ui/jquery-ui.min.js, /assets/lib/bootstrap/js/bootstrap.min.js, /assets/lib/form/jquery.form.js], submitButton:submitButton, roleTypeId:Manager, footer_scripts:[/assets/lib/datetimepicker/js/bootstrap-datetimepicker.min.js, /assets/lib/jquery-validation-1.11.1/dist/jquery.validate.min.js, /assets/lib/chosen/chosen.jquery.min.js, /assets/lib/autosize/jquery.autosize.min.js, /assets/lib/jasny/js/jasny-bootstrap.min.js, /js/jquery-jeditable-1.7.1.min.js, /js/jstree-3.0.3/jstree.min.js, /assets/js/main.min.js, /assets/js/minHeight.js], emplPositionClassId:ProgrammerLead, sri:org.moqui.impl.screen.ScreenRenderImpl@b116dc9, appRoot:hmadmin, thruDate:, fromDate:1265184000000, statusId:WeptUnassigned, html_stylesheets:[], expectationEnumId:, partyId:EX_JOHN_DOE, ec:ExecutionContext]]

**Comment by jonesde** [comment]
The problem was the workEffortId wasn't included in the form submit, the date field is fine. This is fixed in commit #3456dec.

**Comment by jonesde** [comment]
BTW, thank you for reporting this and congratulations on submitting the first HiveMind issue. Good to see more activity here!
